services:
  postgres:
    image: 'postgres:latest'
    container_name: 'pgsql'
    environment:
      - 'POSTGRES_DB=rodovayakniga_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
